# -*- coding: utf-8 -*-
"""people count.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzsYc7ntkQg3dCYWQiARPsrHPdvSNTaA
"""

import os
import shutil
import random

from google.colab import drive
drive.mount('/content/drive')

train_path = "/content/drive/MyDrive/222peopleIntelligentGuard_dataset/train/images"
val_path = "/content/drive/MyDrive/222peopleIntelligentGuard_dataset/val/images"

!git clone https://github.com/ultralytics/yolov5.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5/

!pip install -r requirements.txt

!wget https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5s.pt

!python train.py --img 416 --batch 8 --epochs 100 --data /content/drive/MyDrive/222peopleIntelligentGuard_dataset/222peopleymm.yaml --weights /content/yolov5/yolov5s.pt --nosave --cache

import zipfile
import os

# Directory to download
directory = '/content/yolov5/runs'

# Zip file name
zip_file = '/content/runs.zip'

# Create a zip file containing the directory
with zipfile.ZipFile(zip_file, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(directory):
        for file in files:
            zipf.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), os.path.join(directory, '..')))

# Provide the download link
print("Download the zip file containing the 'runs' directory:")
print(zip_file)

!python detect.py --source /content/p.mp4 --weights /content/yolov5/runs/train/exp/weights/best.pt